CREATE TABLE Customer (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Email VARCHAR(200) UNIQUE NOT NULL,
    Phone VARCHAR(20) NOT NULL,
    StreetAddress VARCHAR(50) NOT NULL,
    PostalCode VARCHAR(15) NOT NULL,
    City VARCHAR(30) NOT NULL,
    Country CHAR(2) NOT NULL,
    Username VARCHAR(50) UNIQUE NOT NULL,
    Password VARCHAR(255) NOT NULL
);
